// src/ui/PlayingCards.svelte
<script lang="ts">
  import './PlayingCards.css';
  import { formatCard, suit, type Card } from '../engine/cards';
  import { fourColorDeck } from '../visual/display';
  import { cardAsset } from './cardAssets';
  let {
    cards,
    hidden = 0,
    highlight = [],
  }: {
    cards: readonly Card[];
    hidden?: number;
    highlight?: readonly Card[];
  } = $props();
  const suits = ['clubs', 'diamonds', 'hearts', 'spades'];
</script>

<div class="playing-cards">
  {#each cards as c (c)}
    <span
      class:out-card={highlight.includes(c)}
      class="playing-card"
      data-suit={suit(c)}
      aria-label={`${formatCard(c)}, ${suits[suit(c)]}`}
    >
      <img src={cardAsset(c, $fourColorDeck)} alt="" draggable="false" />
    </span>
  {/each}
  {#each Array.from({ length: hidden }, (_, i) => i) as i (i)}
    <span class="playing-card card-back" aria-label="Hidden opponent card"
      ><img src={cardAsset()} alt="" draggable="false" /></span
    >
  {/each}
</div>

// src/ui/PlayingCards.tsx
import './PlayingCards.css';
import { formatCard, rank, suit, type Card } from '../engine/cards';
import { suitSymbols, suitNames } from './Card';
export function PlayingCards({
  cards,
  hidden = 0,
  highlight = [],
}: {
  cards: readonly Card[];
  hidden?: number;
  highlight?: readonly Card[];
}) {
  return (
    <div className="playing-cards">
      {cards.map((c) => (
        <span
          key={c}
          className={`playing-card ${highlight.includes(c) ? 'out-card' : ''}`}
          data-suit={suit(c)}
          aria-label={`${formatCard(c)}, ${suitNames[suit(c)]}`}
        >
          <b>{'23456789TJQKA'[rank(c) - 2]}</b>
          <span>{suitSymbols[suit(c)]}</span>
        </span>
      ))}
      {Array.from({ length: hidden }, (_, i) => (
        <span
          key={`hidden${i}`}
          className="playing-card card-back"
          aria-label="Hidden opponent card"
        >
          ♠
        </span>
      ))}
    </div>
  );
}
