// src/App.tsx
import { lazy, Suspense, useEffect, useState } from 'react';
import {
  HashRouter,
  useLocation,
  NavLink,
  Navigate,
  Route,
  Routes,
} from 'react-router';
import { Lab } from './features/lab/Lab';
const DecisionDrills = lazy(() => import('./features/arcade/DecisionDrills'));
const EventBuilder = lazy(() => import('./features/lab/EventBuilder'));
const BankrollLab = lazy(() => import('./features/lab/BankrollLab'));
const RangeLab = lazy(() => import('./features/lab/RangeLab'));
const Stats = lazy(() => import('./features/stats/Stats'));
const Arcade = lazy(() => import('./features/arcade/OutsRush'));
const Play = lazy(() => import('./features/play/Play'));
const Learn = lazy(() => import('./features/learn/Learn'));
const ShuffleLab = lazy(() => import('./features/lab/ShuffleLab'));
const FinalCalculators = lazy(() => import('./features/lab/FinalCalculators'));
const StreakTrap = lazy(() => import('./features/arcade/StreakTrap'));
const Akq = lazy(() => import('./features/arcade/Akq'));
interface Settings {
  theme: 'dark' | 'light';
  fourColor: boolean;
}
function readSettings(): Settings {
  try {
    const s: unknown = JSON.parse(
      localStorage.getItem('holdem-settings') ?? 'null',
    );
    if (
      s &&
      typeof s === 'object' &&
      'theme' in s &&
      'fourColor' in s &&
      (s.theme === 'dark' || s.theme === 'light') &&
      typeof s.fourColor === 'boolean'
    )
      return s as Settings;
  } catch {
    /* Storage may be unavailable. */
  }
  return { theme: 'dark', fourColor: false };
}
const modes = [
  ['learn', 'Learn', 2],
  ['play', 'Play', 3],
  ['lab', 'Lab', 1],
  ['arcade', 'Arcade', 4],
  ['stats', 'Stats', 6],
] as const;
function ToolNavigation() {
  const { pathname } = useLocation();
  const links = pathname.startsWith('/lab')
    ? [
        ['/lab', 'Equity'],
        ['/lab/events', 'Event builder'],
        ['/lab/bankroll', 'Bankroll paths'],
        ['/lab/ranges', 'Ranges'],
        ['/lab/shuffle', 'Shuffle Lab'],
        ['/lab/tools/insurance', 'Insurance'],
        ['/lab/tools/push', 'Push/fold'],
        ['/lab/tools/icm', 'ICM'],
        ['/lab/tools/sizing', 'Kelly'],
      ]
    : pathname.startsWith('/arcade')
      ? [
          ['/arcade', 'Outs Rush'],
          ['/arcade/call', 'Call or Fold'],
          ['/arcade/guess', 'Guess the Equity'],
          ['/arcade/combo', 'Combo Counter'],
          ['/arcade/streak', 'Streak Trap'],
          ['/arcade/akq', 'AKQ game'],
        ]
      : [];
  return links.length ? (
    <nav className="tool-nav" aria-label="Tools">
      {links.map(([to, label]) => (
        <NavLink key={to} to={to} end>
          {label}
        </NavLink>
      ))}
    </nav>
  ) : null;
}
export function App() {
  const [settings, setSettings] = useState(readSettings);
  useEffect(() => {
    document.documentElement.dataset.theme = settings.theme;
    document.documentElement.dataset.fourColor = String(settings.fourColor);
    try {
      localStorage.setItem('holdem-settings', JSON.stringify(settings));
    } catch {
      /* Keep settings in memory when storage is blocked. */
    }
  }, [settings]);
  return (
    <HashRouter>
      <a
        className="skip-link"
        href="#main-content"
        onClick={(e) => {
          e.preventDefault();
          document.getElementById('main-content')?.focus();
        }}
      >
        Skip to content
      </a>
      <header className="app-header">
        <NavLink to="/lab" className="brand">
          <span className="brand-mark">♠</span>
          <span>
            MONTE CARLO<strong>HOLD'EM</strong>
          </span>
        </NavLink>
        <nav aria-label="Main navigation">
          {modes.map(([path, name]) => (
            <NavLink key={path} to={`/${path}`}>
              {name}
            </NavLink>
          ))}
        </nav>
        <details className="settings">
          <summary>Display</summary>
          <div>
            <label>
              <input
                type="checkbox"
                checked={settings.theme === 'light'}
                onChange={(e) =>
                  setSettings({
                    ...settings,
                    theme: e.target.checked ? 'light' : 'dark',
                  })
                }
              />{' '}
              Light theme
            </label>
            <label>
              <input
                type="checkbox"
                checked={settings.fourColor}
                onChange={(e) =>
                  setSettings({ ...settings, fourColor: e.target.checked })
                }
              />{' '}
              Four-color deck
            </label>
          </div>
        </details>
      </header>
      <div id="main-content" tabIndex={-1}>
        <ToolNavigation />
        <Routes>
          <Route
            path="/lab/shuffle"
            element={
              <Suspense fallback={<p>Loading…</p>}>
                <ShuffleLab />
              </Suspense>
            }
          />
          <Route
            path="/lab/tools/:calculator"
            element={
              <Suspense fallback={<p>Loading…</p>}>
                <FinalCalculators />
              </Suspense>
            }
          />
          <Route
            path="/arcade/streak"
            element={
              <Suspense fallback={<p>Loading…</p>}>
                <StreakTrap />
              </Suspense>
            }
          />
          <Route
            path="/arcade/akq"
            element={
              <Suspense fallback={<p>Loading…</p>}>
                <Akq />
              </Suspense>
            }
          />

          <Route path="/lab" element={<Lab />} />
          <Route
            path="/play"
            element={
              <Suspense fallback={<p>Loading table…</p>}>
                <Play />
              </Suspense>
            }
          />
          <Route
            path="/learn"
            element={
              <Suspense fallback={<p>Loading course…</p>}>
                <Learn />
              </Suspense>
            }
          />
          <Route
            path="/learn/:lessonId"
            element={
              <Suspense fallback={<p>Loading lesson…</p>}>
                <Learn />
              </Suspense>
            }
          />
          <Route
            path="/arcade"
            element={
              <Suspense fallback={<p>Loading Outs Rush…</p>}>
                <Arcade />
              </Suspense>
            }
          />
          <Route
            path="/stats"
            element={
              <Suspense fallback={<p>Loading Stats…</p>}>
                <Stats />
              </Suspense>
            }
          />
          <Route
            path="/arcade/:drill"
            element={
              <Suspense fallback={<p>Loading drill…</p>}>
                <DecisionDrills />
              </Suspense>
            }
          />
          <Route
            path="/lab/events"
            element={
              <Suspense fallback={<p>Loading event builder…</p>}>
                <EventBuilder />
              </Suspense>
            }
          />
          <Route
            path="/lab/bankroll"
            element={
              <Suspense fallback={<p>Loading simulator…</p>}>
                <BankrollLab />
              </Suspense>
            }
          />
          <Route
            path="/lab/ranges"
            element={
              <Suspense fallback={<p>Loading range editor…</p>}>
                <RangeLab />
              </Suspense>
            }
          />
          <Route path="*" element={<Navigate to="/lab" replace />} />
        </Routes>
      </div>
      <footer className="app-footer">
        <span>MONTE CARLO HOLD'EM</span>
        <span>Count it. Deal it. Understand it.</span>
      </footer>
    </HashRouter>
  );
}

// src/App.svelte
<script lang="ts">
  import { SITE_NAME } from './decor/site';
  import DecorShell from './decor/DecorShell.svelte';
  import Foundation from './decor/Foundation.svelte';
  import { onMount } from 'svelte';
  import Routes from './Routes.svelte';
  import { navigation, navigate } from './navigation.svelte';
  import { fourColorDeck, theme } from './visual/display';
  const modes = [
    ['play', 'Play'],
    ['learn', 'Course'],
    ['arcade', 'Drills'],
    ['lab', 'Tools'],
    ['stats', 'Progress'],
  ];
  let path = $derived(navigation.path);
  let homeVisit = $state(0);
  function goHome(event: MouseEvent) {
    if (
      event.button !== 0 ||
      event.metaKey ||
      event.ctrlKey ||
      event.shiftKey ||
      event.altKey
    )
      return;
    event.preventDefault();
    navigate('/play');
    // The table and lobby share a URL. A home visit must also reset page state.
    homeVisit += 1;
    window.scrollTo(0, 0);
  }
  function readDeck() {
    try {
      return (
        JSON.parse(localStorage.getItem('holdem-settings') ?? '{}')
          .fourColor === true
      );
    } catch {
      return false;
    }
  }
  function readTheme(): 'dark' | 'blue' {
    try {
      return JSON.parse(localStorage.getItem('holdem-settings') ?? '{}')
        .theme === 'blue'
        ? 'blue'
        : 'dark';
    } catch {
      return 'dark';
    }
  }
  let selectedTheme = $state(readTheme());
  let fourColor = $state(readDeck());
  $effect(() => {
    document.documentElement.dataset.theme = selectedTheme;
    theme.set(selectedTheme);
    document.documentElement.dataset.fourColor = String(fourColor);
    fourColorDeck.set(fourColor);
    try {
      localStorage.setItem(
        'holdem-settings',
        JSON.stringify({ theme: selectedTheme, fourColor }),
      );
    } catch {
      /* Memory-only settings remain available. */
    }
  });
  onMount(() => {
    if (!location.hash) navigate('/play', true);
    const change = () => {
      navigation.sync();
    };
    change();
    window.addEventListener('hashchange', change);
    return () => window.removeEventListener('hashchange', change);
  });
</script>

<Foundation />

<svg class="filter-definitions" aria-hidden="true">
  <defs>
    <linearGradient id="chart-ink" x1="0" y1="1" x2="0" y2="0">
      <stop offset={0} stop-color="var(--violet)" />
      <stop offset={1} stop-color="var(--ice)" />
    </linearGradient>
  </defs>
</svg>
<svg class="film-grain" aria-hidden="true"
  ><filter id="film-grain"
    ><feTurbulence
      type="fractalNoise"
      baseFrequency="0.85"
      numOctaves="3"
      stitchTiles="stitch"
      seed="21"
    /></filter
  ><rect width="100%" height="100%" filter="url(#film-grain)" /></svg
>
<a
  class="skip-link"
  href="#main-content"
  onclick={(e) => {
    e.preventDefault();
    document.getElementById('main-content')?.focus();
  }}>Skip to content</a
>
<header class="app-header">
  <a
    href="#/play"
    class="brand"
    aria-label="contemprorary home"
    onclick={goHome}>{SITE_NAME}</a
  >
  <nav aria-label="Main navigation">
    {#each modes as [route, label] (route)}<a
        href={`#/${route}`}
        class:active={path.startsWith('/' + route)}
        aria-current={path.startsWith('/' + route) ? 'page' : undefined}
        >{label}</a
      >{/each}
  </nav>
  <details class="settings">
    <summary>Display</summary>
    <div class="display-menu">
      <span>Dark theme</span>
      <div class="theme-options" role="group" aria-label="Color theme">
        <button
          aria-pressed={selectedTheme === 'dark'}
          onclick={() => (selectedTheme = 'dark')}>Violet</button
        >
        <button
          aria-pressed={selectedTheme === 'blue'}
          onclick={() => (selectedTheme = 'blue')}>Blue</button
        >
      </div>
      <label
        ><input type="checkbox" bind:checked={fourColor} /> Four-color deck</label
      >
    </div>
  </details>
</header>
<DecorShell><Routes {homeVisit} /></DecorShell>
